# https://travis-ci.org/pySART/pyccp
language: python
sudo: required
python:
    - 3.5
    - 3.6
    - 3.7
    - 3.8
    - "pypy3"

os:
  - linux
  - macos

notifications:
  email: false

install:
  - pip install -r requirements.txt
  - travis_retry pip install pylint codeclimate-test-reporter
  - travis_retry pip install pytest-cov coverage coveralls codacy-coverage

script:
#  python -m unittest discover ./pyccp/tests/
   coverage run --source=pyccp -m unittest discover 

after_success:
  - pylint app
  - coveralls
  - coverage xml && python-codacy-coverage -r coverage.xml
  - codeclimate-test-reporter

